Add docs for FluentBundle
zbraniecki/fluent-rs pull request #1
Opened 2019-01-10 01:33 UTC by JohnHeitmann

Rebase of: https://github.com/projectfluent/fluent-rs/pull/73

2019-01-10 19:56 UTC, zbraniecki requested changes
Thank you! I suggested minor improvements, and I'm happy to merge it once they're applied!

2019-01-10 19:56 UTC, zbraniecki commented on fluent-bundle/src/bundle.rs
>  /// and then `format` it within the bundle.
That requires updating too. We don't have `get_message` anymore, and you just pass a string id to `format`/`format_message` or pass `id.attr` path to `format.

2019-01-10 19:56 UTC, zbraniecki commented on fluent-bundle/src/bundle.rs
> +    /// second term of the return tuple.
If we don't collect any of the errors encountered in the production of the string, it's an implementation shortcoming and I'd prefer not to document it as it indicates the design.

In 0.6 we'll be completing error reporting.

For that reason I'd prefer this sentence to say "Errors produced during message formatting are accumulated in the second tuple field of the Result::Err" or sth like this.

2019-01-10 19:56 UTC, zbraniecki commented on fluent-bundle/src/bundle.rs
> +    /// using `args` to provide variables.
I'd like to add a sentence here like : "This method is useful for cases where the customer wants to apply a compound message onto a UI element."

2019-01-10 19:56 UTC, zbraniecki commented on fluent-bundle/src/bundle.rs
> +    /// second term of the return tuple.
Same comment about errors.

2019-01-11 09:27 UTC, JohnHeitmann commented on fluent-bundle/src/bundle.rs
> +    /// second term of the return tuple.
I reworked this pretty heavily. I tried to make parts of it blurrier (which error cases resulted in which behavior), and other parts more clear (that it's ok to ignore errors if you want).

2019-01-16 20:03 UTC, zbraniecki approved these changes

2019-01-16 20:04 UTC, merged

2019-01-16 20:04 UTC, zbraniecki commented
Thank you!